name: dist-kiss-cross-plat
channels:
  - conda-forge
  - defaults
dependencies:
  - momepy=0.5.3
  - geopandas=0.11.1
  - shapely=1.8.2
  - python=3.9.7
  - pip
  - ipython
  - seaborn=0.13.0
  - pip:
    - agentpy==0.1.5
    - dill==0.3.7
    - multiprocess==0.70.15
    - networkx==2.8.8
    - pandas==1.3.4
    - salib==1.4.7